@endpoint = http://localhost:{{$dotenv PORT}}


# POST {{endpoint}}/api/createUser
# content-type: application/json

# {
#   "pseudo": "Toto",
#   "email": "toto@toto.fr",
#   "birthday": "12/05/1990",
#   "password": "toto"
# }



# POST {{endpoint}}/api/login
# content-type: application/json

# {
#   "pseudo": "Toto",
#   "password": "toto"
# }



# POST {{endpoint}}/api/findUser
# content-type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJwc2V1ZG8iOiJUb3RvIiwiZW1haWwiOiJ0b3RvQHRvdG8uZnIiLCJiaXJ0aGRheSI6IjE5OTAtMDUtMTFUMjI6MDA6MDAuMDAwWiIsImNyZWF0ZWRfYXQiOiIyMDI0LTA0LTE1VDEzOjMxOjU4Ljk3M1oiLCJ1cGRhdGVkX2F0IjpudWxsfSwiaWF0IjoxNzEzMTg3OTYwfQ.3PV9GWk_s6FvT_N4QsUllswPrXRESYcVAgaOEABHd2Q

# {
#   "pseudo": "Toto"
# }



# DELETE {{endpoint}}/api/deleteUser/2
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJwc2V1ZG8iOiJUb3RvIiwiZW1haWwiOiJ0b3RvQHRvdG8uZnIiLCJiaXJ0aGRheSI6IjE5OTAtMDUtMTFUMjI6MDA6MDAuMDAwWiIsImNyZWF0ZWRfYXQiOiIyMDI0LTA0LTE1VDEzOjMxOjU4Ljk3M1oiLCJ1cGRhdGVkX2F0IjpudWxsfSwiaWF0IjoxNzEzMTg3OTYwfQ.3PV9GWk_s6FvT_N4QsUllswPrXRESYcVAgaOEABHd2Q



# PATCH {{endpoint}}/api/updateUser/1
# content-type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJwc2V1ZG8iOiJUb3RvIiwiZW1haWwiOiJ0b3RvQHRvdG8uZnIiLCJiaXJ0aGRheSI6IjE5OTAtMDUtMTFUMjI6MDA6MDAuMDAwWiIsImNyZWF0ZWRfYXQiOiIyMDI0LTA0LTE1VDEzOjMxOjU4Ljk3M1oiLCJ1cGRhdGVkX2F0IjpudWxsfSwiaWF0IjoxNzEzMTg3OTYwfQ.3PV9GWk_s6FvT_N4QsUllswPrXRESYcVAgaOEABHd2Q

# {
#   "pseudo": "tata",
#   "email": "tata@tata.fr",
#   "birthday": "1991/05/25",
#   "password": "tata"
# }



POST {{endpoint}}/api/addToFavorite
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJwc2V1ZG8iOiJUb3RvIiwiZW1haWwiOiJ0b3RvQHRvdG8uZnIiLCJiaXJ0aGRheSI6IjE5OTAtMDUtMTFUMjI6MDA6MDAuMDAwWiIsImNyZWF0ZWRfYXQiOiIyMDI0LTA0LTE1VDEzOjQ5OjE2LjA4MFoiLCJ1cGRhdGVkX2F0IjpudWxsfSwiaWF0IjoxNzEzMTg5MDYzfQ._YpwrZ0GrmcNMQjXvaUnvcsZg5L0o0igAOjEceMkZts

{
  "userId": 1,
  "movieId": 3,
  "title": "machin",
  "poster_path": "machin",
  "overview": "machin",
  "genres": ["machin"]
}



# POST {{endpoint}}/api/addToToReview
# content-type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJwc2V1ZG8iOiJUb3RvIiwiZW1haWwiOiJ0b3RvQHRvdG8uZnIiLCJiaXJ0aGRheSI6IjE5OTAtMDUtMTFUMjI6MDA6MDAuMDAwWiIsImNyZWF0ZWRfYXQiOiIyMDI0LTA0LTE1VDEzOjQ5OjE2LjA4MFoiLCJ1cGRhdGVkX2F0IjpudWxsfSwiaWF0IjoxNzEzMTg5MDYzfQ._YpwrZ0GrmcNMQjXvaUnvcsZg5L0o0igAOjEceMkZts

# {
#   "userId": 1,
#   "movieId": 5,
#   "title": "Star Wars",
#   "poster_path": "Chemin des étoiles",
#   "overview": "Il était une fois, une étoile...",
#   "genres": ["science-fiction"]
# }



# GET {{endpoint}}/api/showFavorite/1
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJwc2V1ZG8iOiJUb3RvIiwiZW1haWwiOiJ0b3RvQHRvdG8uZnIiLCJiaXJ0aGRheSI6IjE5OTAtMDUtMTFUMjI6MDA6MDAuMDAwWiIsImNyZWF0ZWRfYXQiOiIyMDI0LTA0LTE1VDEzOjMxOjU4Ljk3M1oiLCJ1cGRhdGVkX2F0IjpudWxsfSwiaWF0IjoxNzEzMTg3OTYwfQ.3PV9GWk_s6FvT_N4QsUllswPrXRESYcVAgaOEABHd2Q



# GET {{endpoint}}/api/showToReview/1
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJwc2V1ZG8iOiJUb3RvIiwiZW1haWwiOiJ0b3RvQHRvdG8uZnIiLCJiaXJ0aGRheSI6IjE5OTAtMDUtMTFUMjI6MDA6MDAuMDAwWiIsImNyZWF0ZWRfYXQiOiIyMDI0LTA0LTE1VDEzOjMxOjU4Ljk3M1oiLCJ1cGRhdGVkX2F0IjpudWxsfSwiaWF0IjoxNzEzMTg3OTYwfQ.3PV9GWk_s6FvT_N4QsUllswPrXRESYcVAgaOEABHd2Q



#  DELETE {{endpoint}}/api/deleteFromToReview
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJwc2V1ZG8iOiJUb3RvIiwiZW1haWwiOiJ0b3RvQHRvdG8uZnIiLCJiaXJ0aGRheSI6IjE5OTAtMDUtMTFUMjI6MDA6MDAuMDAwWiIsImNyZWF0ZWRfYXQiOiIyMDI0LTA0LTE1VDEzOjMxOjU4Ljk3M1oiLCJ1cGRhdGVkX2F0IjpudWxsfSwiaWF0IjoxNzEzMTg3OTYwfQ.3PV9GWk_s6FvT_N4QsUllswPrXRESYcVAgaOEABHd2Q
# {
#   "userId": 1,
#   "movieId": 5
# }



# POST {{endpoint}}/api/addGroup
# content-type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJwc2V1ZG8iOiJUb3RvIiwiZW1haWwiOiJ0b3RvQHRvdG8uZnIiLCJiaXJ0aGRheSI6IjE5OTAtMDUtMTFUMjI6MDA6MDAuMDAwWiIsImNyZWF0ZWRfYXQiOiIyMDI0LTA0LTE1VDEzOjMxOjU4Ljk3M1oiLCJ1cGRhdGVkX2F0IjpudWxsfSwiaWF0IjoxNzEzMTg3OTYwfQ.3PV9GWk_s6FvT_N4QsUllswPrXRESYcVAgaOEABHd2Q

# {
#   "name": "BandOmovies2"
# }



#  GET {{endpoint}}/api/group
#  Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJwc2V1ZG8iOiJUb3RvIiwiZW1haWwiOiJ0b3RvQHRvdG8uZnIiLCJiaXJ0aGRheSI6IjE5OTAtMDUtMTFUMjI6MDA6MDAuMDAwWiIsImNyZWF0ZWRfYXQiOiIyMDI0LTA0LTE1VDEzOjMxOjU4Ljk3M1oiLCJ1cGRhdGVkX2F0IjpudWxsfSwiaWF0IjoxNzEzMTg3OTYwfQ.3PV9GWk_s6FvT_N4QsUllswPrXRESYcVAgaOEABHd2Q



# POST {{endpoint}}/api/findUser
# content-type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJwc2V1ZG8iOiJUb3RvIiwiZW1haWwiOiJ0b3RvQHRvdG8uZnIiLCJiaXJ0aGRheSI6IjE5OTAtMDUtMTFUMjI6MDA6MDAuMDAwWiIsImNyZWF0ZWRfYXQiOiIyMDI0LTA0LTE1VDEzOjMxOjU4Ljk3M1oiLCJ1cGRhdGVkX2F0IjpudWxsfSwiaWF0IjoxNzEzMTg3OTYwfQ.3PV9GWk_s6FvT_N4QsUllswPrXRESYcVAgaOEABHd2Q

# {
#   "pseudo": "Yuki"
# }



# PATCH {{endpoint}}/api/addToGroup
# content-type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJwc2V1ZG8iOiJUb3RvIiwiZW1haWwiOiJ0b3RvQHRvdG8uZnIiLCJiaXJ0aGRheSI6IjE5OTAtMDUtMTFUMjI6MDA6MDAuMDAwWiIsImNyZWF0ZWRfYXQiOiIyMDI0LTA0LTE1VDEzOjMxOjU4Ljk3M1oiLCJ1cGRhdGVkX2F0IjpudWxsfSwiaWF0IjoxNzEzMTg3OTYwfQ.3PV9GWk_s6FvT_N4QsUllswPrXRESYcVAgaOEABHd2Q

# {
#   "groupId": 2,
#   "pseudo": "Yuki"
# }



# GET {{endpoint}}/api/groupUsers/2
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJwc2V1ZG8iOiJUb3RvIiwiZW1haWwiOiJ0b3RvQHRvdG8uZnIiLCJiaXJ0aGRheSI6IjE5OTAtMDUtMTFUMjI6MDA6MDAuMDAwWiIsImNyZWF0ZWRfYXQiOiIyMDI0LTA0LTE1VDEzOjMxOjU4Ljk3M1oiLCJ1cGRhdGVkX2F0IjpudWxsfSwiaWF0IjoxNzEzMTg3OTYwfQ.3PV9GWk_s6FvT_N4QsUllswPrXRESYcVAgaOEABHd2Q



# PATCH {{endpoint}}/api/removeToGroup
# content-type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJwc2V1ZG8iOiJUb3RvIiwiZW1haWwiOiJ0b3RvQHRvdG8uZnIiLCJiaXJ0aGRheSI6IjE5OTAtMDUtMTFUMjI6MDA6MDAuMDAwWiIsImNyZWF0ZWRfYXQiOiIyMDI0LTA0LTE1VDEzOjMxOjU4Ljk3M1oiLCJ1cGRhdGVkX2F0IjpudWxsfSwiaWF0IjoxNzEzMTg3OTYwfQ.3PV9GWk_s6FvT_N4QsUllswPrXRESYcVAgaOEABHd2Q

# {
#   "groupId": 2,
#   "pseudo": "Yuki"
# }



#  DELETE {{endpoint}}/api/deleteGroup/2
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJwc2V1ZG8iOiJUb3RvIiwiZW1haWwiOiJ0b3RvQHRvdG8uZnIiLCJiaXJ0aGRheSI6IjE5OTAtMDUtMTFUMjI6MDA6MDAuMDAwWiIsImNyZWF0ZWRfYXQiOiIyMDI0LTA0LTE1VDEzOjMxOjU4Ljk3M1oiLCJ1cGRhdGVkX2F0IjpudWxsfSwiaWF0IjoxNzEzMTg3OTYwfQ.3PV9GWk_s6FvT_N4QsUllswPrXRESYcVAgaOEABHd2Q



# POST {{endpoint}}/api/createVote
# content-type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJwc2V1ZG8iOiJUb3RvIiwiZW1haWwiOiJ0b3RvQHRvdG8uZnIiLCJiaXJ0aGRheSI6IjE5OTAtMDUtMTFUMjI6MDA6MDAuMDAwWiIsImNyZWF0ZWRfYXQiOiIyMDI0LTA0LTE1VDEzOjMxOjU4Ljk3M1oiLCJ1cGRhdGVkX2F0IjpudWxsfSwiaWF0IjoxNzEzMTg3OTYwfQ.3PV9GWk_s6FvT_N4QsUllswPrXRESYcVAgaOEABHd2Q

# {
#   "pseudo": "Yuki"
# }