@endpoint = http://localhost:{{$dotenv PORT}}


# POST {{endpoint}}/api/createUser
# content-type: application/json

# {
#   "pseudo": "Toto",
#   "email": "toto@toto.fr",
#   "birthday": "12/05/1990",
#   "password": "toto"
# }



# POST {{endpoint}}/api/login
# content-type: application/json

# {
#   "pseudo": "Toto",
#   "password": "toto"
# }



# POST {{endpoint}}/api/findUser
# content-type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJwc2V1ZG8iOiJUb3RvIiwiZW1haWwiOiJ0b3RvQHRvdG8uZnIiLCJiaXJ0aGRheSI6IjE5OTAtMDUtMTFUMjI6MDA6MDAuMDAwWiIsImNyZWF0ZWRfYXQiOiIyMDI0LTA0LTE2VDA5OjM0OjEyLjE1M1oiLCJ1cGRhdGVkX2F0IjpudWxsfSwiaWF0IjoxNzEzMjYwMTU2fQ.5SXuNKjXcrFp7BJpzkT_EB5LsUZ_RvmzP8uXsNx17sA

# {
#   "pseudo": "Toto"
# }



# DELETE {{endpoint}}/api/deleteUser/2
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJwc2V1ZG8iOiJUb3RvIiwiZW1haWwiOiJ0b3RvQHRvdG8uZnIiLCJiaXJ0aGRheSI6IjE5OTAtMDUtMTFUMjI6MDA6MDAuMDAwWiIsImNyZWF0ZWRfYXQiOiIyMDI0LTA0LTE2VDA5OjM0OjEyLjE1M1oiLCJ1cGRhdGVkX2F0IjpudWxsfSwiaWF0IjoxNzEzMjYwMTU2fQ.5SXuNKjXcrFp7BJpzkT_EB5LsUZ_RvmzP8uXsNx17sA



# PATCH {{endpoint}}/api/updateUser/1
# content-type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJwc2V1ZG8iOiJUb3RvIiwiZW1haWwiOiJ0b3RvQHRvdG8uZnIiLCJiaXJ0aGRheSI6IjE5OTAtMDUtMTFUMjI6MDA6MDAuMDAwWiIsImNyZWF0ZWRfYXQiOiIyMDI0LTA0LTE2VDA5OjM0OjEyLjE1M1oiLCJ1cGRhdGVkX2F0IjpudWxsfSwiaWF0IjoxNzEzMjYwMTU2fQ.5SXuNKjXcrFp7BJpzkT_EB5LsUZ_RvmzP8uXsNx17sA

# {
#   "pseudo": "tata",
#   "email": "tata@tata.fr",
#   "birthday": "1991/05/25",
#   "password": "tata"
# }



# POST {{endpoint}}/api/addToFavorite
# content-type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJwc2V1ZG8iOiJUb3RvIiwiZW1haWwiOiJ0b3RvQHRvdG8uZnIiLCJiaXJ0aGRheSI6IjE5OTAtMDUtMTFUMjI6MDA6MDAuMDAwWiIsImNyZWF0ZWRfYXQiOiIyMDI0LTA0LTE2VDA5OjM0OjEyLjE1M1oiLCJ1cGRhdGVkX2F0IjpudWxsfSwiaWF0IjoxNzEzMjYwMTU2fQ.5SXuNKjXcrFp7BJpzkT_EB5LsUZ_RvmzP8uXsNx17sA

# {
#   "userId": 1,
#   "movieId": 4,
#   "title": "bidule",
#   "poster_path": "bidule",
#   "overview": "bidule",
#   "genres": ["bidule", "test"]
# }



# POST {{endpoint}}/api/addToToReview
# content-type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJwc2V1ZG8iOiJUb3RvIiwiZW1haWwiOiJ0b3RvQHRvdG8uZnIiLCJiaXJ0aGRheSI6IjE5OTAtMDUtMTFUMjI6MDA6MDAuMDAwWiIsImNyZWF0ZWRfYXQiOiIyMDI0LTA0LTE2VDA5OjM0OjEyLjE1M1oiLCJ1cGRhdGVkX2F0IjpudWxsfSwiaWF0IjoxNzEzMjYwMTU2fQ.5SXuNKjXcrFp7BJpzkT_EB5LsUZ_RvmzP8uXsNx17sA

# {
#   "userId": 1,
#   "movieId": 5,
#   "title": "Star Wars",
#   "poster_path": "Chemin des étoiles",
#   "overview": "Il était une fois, une étoile...",
#   "genres": ["science-fiction"]
# }



POST {{endpoint}}/api/showFavoriteByGenre/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJwc2V1ZG8iOiJUb3RvIiwiZW1haWwiOiJ0b3RvQHRvdG8uZnIiLCJiaXJ0aGRheSI6IjE5OTAtMDUtMTFUMjI6MDA6MDAuMDAwWiIsImNyZWF0ZWRfYXQiOiIyMDI0LTA0LTE2VDA5OjM0OjEyLjE1M1oiLCJ1cGRhdGVkX2F0IjpudWxsfSwiaWF0IjoxNzEzMjYwMTU2fQ.5SXuNKjXcrFp7BJpzkT_EB5LsUZ_RvmzP8uXsNx17sA

{
  "genre": "machin"
}


# GET {{endpoint}}/api/showToReview/1
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJwc2V1ZG8iOiJUb3RvIiwiZW1haWwiOiJ0b3RvQHRvdG8uZnIiLCJiaXJ0aGRheSI6IjE5OTAtMDUtMTFUMjI6MDA6MDAuMDAwWiIsImNyZWF0ZWRfYXQiOiIyMDI0LTA0LTE2VDA5OjM0OjEyLjE1M1oiLCJ1cGRhdGVkX2F0IjpudWxsfSwiaWF0IjoxNzEzMjYwMTU2fQ.5SXuNKjXcrFp7BJpzkT_EB5LsUZ_RvmzP8uXsNx17sA



#  DELETE {{endpoint}}/api/deleteFromToReview
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJwc2V1ZG8iOiJUb3RvIiwiZW1haWwiOiJ0b3RvQHRvdG8uZnIiLCJiaXJ0aGRheSI6IjE5OTAtMDUtMTFUMjI6MDA6MDAuMDAwWiIsImNyZWF0ZWRfYXQiOiIyMDI0LTA0LTE2VDA5OjM0OjEyLjE1M1oiLCJ1cGRhdGVkX2F0IjpudWxsfSwiaWF0IjoxNzEzMjYwMTU2fQ.5SXuNKjXcrFp7BJpzkT_EB5LsUZ_RvmzP8uXsNx17sA
# {
#   "userId": 1,
#   "movieId": 5
# }



# POST {{endpoint}}/api/addGroup
# content-type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJwc2V1ZG8iOiJUb3RvIiwiZW1haWwiOiJ0b3RvQHRvdG8uZnIiLCJiaXJ0aGRheSI6IjE5OTAtMDUtMTFUMjI6MDA6MDAuMDAwWiIsImNyZWF0ZWRfYXQiOiIyMDI0LTA0LTE2VDA5OjM0OjEyLjE1M1oiLCJ1cGRhdGVkX2F0IjpudWxsfSwiaWF0IjoxNzEzMjYwMTU2fQ.5SXuNKjXcrFp7BJpzkT_EB5LsUZ_RvmzP8uXsNx17sA

# {
#   "name": "BandOmovies2"
# }



#  GET {{endpoint}}/api/group
#  Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJwc2V1ZG8iOiJUb3RvIiwiZW1haWwiOiJ0b3RvQHRvdG8uZnIiLCJiaXJ0aGRheSI6IjE5OTAtMDUtMTFUMjI6MDA6MDAuMDAwWiIsImNyZWF0ZWRfYXQiOiIyMDI0LTA0LTE2VDA5OjM0OjEyLjE1M1oiLCJ1cGRhdGVkX2F0IjpudWxsfSwiaWF0IjoxNzEzMjYwMTU2fQ.5SXuNKjXcrFp7BJpzkT_EB5LsUZ_RvmzP8uXsNx17sA



# POST {{endpoint}}/api/findUser
# content-type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJwc2V1ZG8iOiJUb3RvIiwiZW1haWwiOiJ0b3RvQHRvdG8uZnIiLCJiaXJ0aGRheSI6IjE5OTAtMDUtMTFUMjI6MDA6MDAuMDAwWiIsImNyZWF0ZWRfYXQiOiIyMDI0LTA0LTE2VDA5OjM0OjEyLjE1M1oiLCJ1cGRhdGVkX2F0IjpudWxsfSwiaWF0IjoxNzEzMjYwMTU2fQ.5SXuNKjXcrFp7BJpzkT_EB5LsUZ_RvmzP8uXsNx17sA

# {
#   "pseudo": "Yuki"
# }



# PATCH {{endpoint}}/api/addToGroup
# content-type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJwc2V1ZG8iOiJUb3RvIiwiZW1haWwiOiJ0b3RvQHRvdG8uZnIiLCJiaXJ0aGRheSI6IjE5OTAtMDUtMTFUMjI6MDA6MDAuMDAwWiIsImNyZWF0ZWRfYXQiOiIyMDI0LTA0LTE2VDA5OjM0OjEyLjE1M1oiLCJ1cGRhdGVkX2F0IjpudWxsfSwiaWF0IjoxNzEzMjYwMTU2fQ.5SXuNKjXcrFp7BJpzkT_EB5LsUZ_RvmzP8uXsNx17sA

# {
#   "groupId": 2,
#   "pseudo": "Yuki"
# }



# GET {{endpoint}}/api/groupUsers/2
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJwc2V1ZG8iOiJUb3RvIiwiZW1haWwiOiJ0b3RvQHRvdG8uZnIiLCJiaXJ0aGRheSI6IjE5OTAtMDUtMTFUMjI6MDA6MDAuMDAwWiIsImNyZWF0ZWRfYXQiOiIyMDI0LTA0LTE2VDA5OjM0OjEyLjE1M1oiLCJ1cGRhdGVkX2F0IjpudWxsfSwiaWF0IjoxNzEzMjYwMTU2fQ.5SXuNKjXcrFp7BJpzkT_EB5LsUZ_RvmzP8uXsNx17sA



# PATCH {{endpoint}}/api/removeToGroup
# content-type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJwc2V1ZG8iOiJUb3RvIiwiZW1haWwiOiJ0b3RvQHRvdG8uZnIiLCJiaXJ0aGRheSI6IjE5OTAtMDUtMTFUMjI6MDA6MDAuMDAwWiIsImNyZWF0ZWRfYXQiOiIyMDI0LTA0LTE2VDA5OjM0OjEyLjE1M1oiLCJ1cGRhdGVkX2F0IjpudWxsfSwiaWF0IjoxNzEzMjYwMTU2fQ.5SXuNKjXcrFp7BJpzkT_EB5LsUZ_RvmzP8uXsNx17sA

# {
#   "groupId": 2,
#   "pseudo": "Yuki"
# }



#  DELETE {{endpoint}}/api/deleteGroup/2
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJwc2V1ZG8iOiJUb3RvIiwiZW1haWwiOiJ0b3RvQHRvdG8uZnIiLCJiaXJ0aGRheSI6IjE5OTAtMDUtMTFUMjI6MDA6MDAuMDAwWiIsImNyZWF0ZWRfYXQiOiIyMDI0LTA0LTE2VDA5OjM0OjEyLjE1M1oiLCJ1cGRhdGVkX2F0IjpudWxsfSwiaWF0IjoxNzEzMjYwMTU2fQ.5SXuNKjXcrFp7BJpzkT_EB5LsUZ_RvmzP8uXsNx17sA



# POST {{endpoint}}/api/createVote
# content-type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJwc2V1ZG8iOiJUb3RvIiwiZW1haWwiOiJ0b3RvQHRvdG8uZnIiLCJiaXJ0aGRheSI6IjE5OTAtMDUtMTFUMjI6MDA6MDAuMDAwWiIsImNyZWF0ZWRfYXQiOiIyMDI0LTA0LTE2VDA5OjM0OjEyLjE1M1oiLCJ1cGRhdGVkX2F0IjpudWxsfSwiaWF0IjoxNzEzMjYwMTU2fQ.5SXuNKjXcrFp7BJpzkT_EB5LsUZ_RvmzP8uXsNx17sA

# {
#   "pseudo": "Yuki"
# }