@endpoint = http://localhost:{{$dotenv PORT}}


# POST {{endpoint}}/api/user
# content-type: application/json

# {
#   "pseudo": "Toto",
#   "email": "toto@toto.fr",
#   "date_of_birth": "12/05/1990",
#   "password": "toto"
# }



# POST {{endpoint}}/api/login
# content-type: application/json

# {
#   "pseudo": "Toto",
#   "password": "toto"
# }



# DELETE {{endpoint}}/api/user/2



# PATCH {{endpoint}}/api/user
# content-type: application/json

# {
#   "id": 1,
#   "pseudo": "toutou",
#   "email": "blanc@vert.fr",
#   "date_of_birth": "04/04/2020",
#   "password": "orange"
# }



# POST {{endpoint}}/api/addToList
# content-type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJwc2V1ZG8iOiJUb3RvIiwiZW1haWwiOiJ0b3RvQHRvdG8uZnIiLCJkYXRlX29mX2JpcnRoIjoiMTk5MC0wNS0xMVQyMjowMDowMC4wMDBaIiwibGlzdCI6W3sibmFtZSI6IlN0YXIgV2FycyIsInBpY3R1cmUiOiJDaGVtaW4gZGVzIMOpdG9pbGVzIn1dLCJ0b19yZXZpZXciOlt7Im5hbWUiOiJJbmNlcHRpb24iLCJwaWN0dXJlIjoiQ2hlbWluIGRlIGxhIHRvdXBpZSJ9XSwiZ3JvdXBfaWQiOm51bGwsImNyZWF0ZWRfYXQiOiIyMDI0LTA0LTEwVDA4OjA0OjM0LjI4NFoiLCJ1cGRhdGVkX2F0IjpudWxsfSwiaWF0IjoxNzEyNzUwNDQxfQ.S1Nr7P9h9wpLgVaO1Oa4wW7jOF8byx0DLQ6oXd2hWew

# {
#   "id": 1,
#   "title": "Star Wars",
#   "poster_path": "Chemin des étoiles",
#   "overview": "Il était une fois, une étoile...",
#   "genres": ["Action, Science_fiction"]
# }



# POST {{endpoint}}/api/addToToReview
# content-type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJwc2V1ZG8iOiJUb3RvIiwiZW1haWwiOiJ0b3RvQHRvdG8uZnIiLCJkYXRlX29mX2JpcnRoIjoiMTk5MC0wNS0xMVQyMjowMDowMC4wMDBaIiwibGlzdCI6W3sibmFtZSI6IlN0YXIgV2FycyIsInBpY3R1cmUiOiJDaGVtaW4gZGVzIMOpdG9pbGVzIn1dLCJ0b19yZXZpZXciOlt7Im5hbWUiOiJJbmNlcHRpb24iLCJwaWN0dXJlIjoiQ2hlbWluIGRlIGxhIHRvdXBpZSJ9XSwiZ3JvdXBfaWQiOm51bGwsImNyZWF0ZWRfYXQiOiIyMDI0LTA0LTEwVDA4OjA0OjM0LjI4NFoiLCJ1cGRhdGVkX2F0IjpudWxsfSwiaWF0IjoxNzEyNzUwNDQxfQ.S1Nr7P9h9wpLgVaO1Oa4wW7jOF8byx0DLQ6oXd2hWew

# {
#   "id": 1,
#   "title": "Spirit",
#   "poster_path": "Chemin de l'écurie",
#   "overview": "Il était une fois, un dada...",
#   "genres": ["Familial, Comédie"]
# }



# GET {{endpoint}}/api/list
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJwc2V1ZG8iOiJUb3RvIiwiZW1haWwiOiJ0b3RvQHRvdG8uZnIiLCJkYXRlX29mX2JpcnRoIjoiMTk5MC0wNS0xMVQyMjowMDowMC4wMDBaIiwibGlzdCI6W3sibmFtZSI6IlN0YXIgV2FycyIsInBpY3R1cmUiOiJDaGVtaW4gZGVzIMOpdG9pbGVzIn1dLCJ0b19yZXZpZXciOlt7Im5hbWUiOiJJbmNlcHRpb24iLCJwaWN0dXJlIjoiQ2hlbWluIGRlIGxhIHRvdXBpZSJ9XSwiZ3JvdXBfaWQiOm51bGwsImNyZWF0ZWRfYXQiOiIyMDI0LTA0LTEwVDA4OjA0OjM0LjI4NFoiLCJ1cGRhdGVkX2F0IjpudWxsfSwiaWF0IjoxNzEyNzUwNDQxfQ.S1Nr7P9h9wpLgVaO1Oa4wW7jOF8byx0DLQ6oXd2hWew



# GET {{endpoint}}/api/toReview
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJwc2V1ZG8iOiJUb3RvIiwiZW1haWwiOiJ0b3RvQHRvdG8uZnIiLCJkYXRlX29mX2JpcnRoIjoiMTk5MC0wNS0xMVQyMjowMDowMC4wMDBaIiwibGlzdCI6W3sibmFtZSI6IlN0YXIgV2FycyIsInBpY3R1cmUiOiJDaGVtaW4gZGVzIMOpdG9pbGVzIn1dLCJ0b19yZXZpZXciOlt7Im5hbWUiOiJJbmNlcHRpb24iLCJwaWN0dXJlIjoiQ2hlbWluIGRlIGxhIHRvdXBpZSJ9XSwiZ3JvdXBfaWQiOm51bGwsImNyZWF0ZWRfYXQiOiIyMDI0LTA0LTEwVDA4OjA0OjM0LjI4NFoiLCJ1cGRhdGVkX2F0IjpudWxsfSwiaWF0IjoxNzEyNzUwNDQxfQ.S1Nr7P9h9wpLgVaO1Oa4wW7jOF8byx0DLQ6oXd2hWew



#  DELETE {{endpoint}}/api/deleteFromToReview
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJwc2V1ZG8iOiJUb3RvIiwiZW1haWwiOiJ0b3RvQHRvdG8uZnIiLCJkYXRlX29mX2JpcnRoIjoiMTk5MC0wNS0xMVQyMjowMDowMC4wMDBaIiwibGlzdCI6W3sibmFtZSI6IlN0YXIgV2FycyIsInBpY3R1cmUiOiJDaGVtaW4gZGVzIMOpdG9pbGVzIn1dLCJ0b19yZXZpZXciOlt7Im5hbWUiOiJJbmNlcHRpb24iLCJwaWN0dXJlIjoiQ2hlbWluIGRlIGxhIHRvdXBpZSJ9XSwiZ3JvdXBfaWQiOm51bGwsImNyZWF0ZWRfYXQiOiIyMDI0LTA0LTEwVDA4OjA0OjM0LjI4NFoiLCJ1cGRhdGVkX2F0IjpudWxsfSwiaWF0IjoxNzEyNzUwNDQxfQ.S1Nr7P9h9wpLgVaO1Oa4wW7jOF8byx0DLQ6oXd2hWew

# {
#   "title": "Spirit",
#   "poster_path": "Chemin de l'écurie"
# }



# POST {{endpoint}}/api/addGroup
# content-type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJwc2V1ZG8iOiJUb3RvIiwiZW1haWwiOiJ0b3RvQHRvdG8uZnIiLCJkYXRlX29mX2JpcnRoIjoiMTk5MC0wNS0xMVQyMjowMDowMC4wMDBaIiwibGlzdCI6W3sibmFtZSI6IlN0YXIgV2FycyIsInBpY3R1cmUiOiJDaGVtaW4gZGVzIMOpdG9pbGVzIn1dLCJ0b19yZXZpZXciOlt7Im5hbWUiOiJJbmNlcHRpb24iLCJwaWN0dXJlIjoiQ2hlbWluIGRlIGxhIHRvdXBpZSJ9XSwiZ3JvdXBfaWQiOm51bGwsImNyZWF0ZWRfYXQiOiIyMDI0LTA0LTEwVDA4OjA0OjM0LjI4NFoiLCJ1cGRhdGVkX2F0IjpudWxsfSwiaWF0IjoxNzEyNzUwNDQxfQ.S1Nr7P9h9wpLgVaO1Oa4wW7jOF8byx0DLQ6oXd2hWew

# {
#   "name": "BandOmovies2"
# }



#  GET {{endpoint}}/api/group
#  Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJwc2V1ZG8iOiJUb3RvIiwiZW1haWwiOiJ0b3RvQHRvdG8uZnIiLCJkYXRlX29mX2JpcnRoIjoiMTk5MC0wNS0xMVQyMjowMDowMC4wMDBaIiwibGlzdCI6W3sibmFtZSI6IlN0YXIgV2FycyIsInBpY3R1cmUiOiJDaGVtaW4gZGVzIMOpdG9pbGVzIn1dLCJ0b19yZXZpZXciOlt7Im5hbWUiOiJJbmNlcHRpb24iLCJwaWN0dXJlIjoiQ2hlbWluIGRlIGxhIHRvdXBpZSJ9XSwiZ3JvdXBfaWQiOm51bGwsImNyZWF0ZWRfYXQiOiIyMDI0LTA0LTEwVDA4OjA0OjM0LjI4NFoiLCJ1cGRhdGVkX2F0IjpudWxsfSwiaWF0IjoxNzEyNzUwNDQxfQ.S1Nr7P9h9wpLgVaO1Oa4wW7jOF8byx0DLQ6oXd2hWew